### ISSUE TITLE
error：循环链表-在任意位置移除元素

### ISSUE THREAD

**Issue by zhaoaaaaa5** [wangtunan/blog#11]
`removeAt (index) {
  if (index >= 0 && index < this.count) {
    let current = this.head
    if (index === 0) {
      if (this.count === 0) {
        this.head = null
      } else {
        const removed = this.head
        current = this.getElementAt(this.count - 1)
        this.head = this.head.next
        current.next = this.head
        current = removed
      }
    } else {
      const previous = this.getElementAt(index - 1)
      current = previous.next
      previous.next = previous.next
    }
    this.count--
    return current.element
  }
  return undefined
}`

previous.next = previous.next 这句话是不是错了，不应该是 previous.next = current.next 吗

**Comment by wangtunan** [comment]
感谢勘误，确实错了
